<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
	<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	<Authors>Jermy Hernandez</Authors>
	<Company>Nominal Solutions LLC</Company>
	<Version>0.0.2-beta</Version>
	<Description>JobManager for Hangfire is a job queue manager designed to be able to dynamically manage jobs from SQL Server.</Description>
	<Copyright />
	<PackageProjectUrl>https://github.com/NominalSolutions/NomSol.Hangfire.JobManager</PackageProjectUrl>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/NominalSolutions/NomSol.Hangfire.JobManager</RepositoryUrl>
	<RepositoryType>Git</RepositoryType>
	<PackageTags>hangfire jobs manager</PackageTags>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NomSol.Hangfire.JobManager.Core\NomSol.Hangfire.JobManager.Core.csproj" />
  </ItemGroup>

</Project>
